#!/bin/bash

if [[ "$1" == "" ]]; then
    echo Usage: rust-ctags dirs...
    exit 1
fi

MYDIR="$(dirname $0)"
CTAGS="$MYDIR/ctags.rust"

# case when rust-ctags in PATH
if [ ! -f "$CTAGS" ]; then
  ME="$(readlink $0)" # check if it symlinked
  ME="${ME:-$0}" # or just $0 by default
  CTAGS="$(dirname $ME)/ctags.rust"
fi

if [ ! -f "$CTAGS" ]; then
  echo ctags.rust definition not found
  echo Searched at: "$CTAGS"
  exit 1
fi

rm -f TAGS

for SRCDIR in "$@"; do
    echo "Indexing $SRCDIR"

    if [ ! -d "$SRCDIR" ]; then
        echo Source directory "'"$SRCDIR"'" not found.
        exit 1
    fi

    ctags -a -e -f TAGS --options="$CTAGS" --languages=Rust --recurse "$SRCDIR"
done
